formatter: "markdown table"

sort:
  enable: true
  by: required

sections:
  show:
  - inputs
  - outputs
  - providers
  - requirements

content: |-
  {{ include "examples/main.description" }}

  ## Example

  ```hcl
  {{ include "examples/main.example" }}
  ```

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}
  
  ![Alt](https://repobeats.axiom.co/api/embed/d5c6fd467a9febbf9bea34fbcd6eb31174975075.svg "Repobeats analytics image")

output:
  file: "README.md"
